#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <kernel-source-dir>" >&2
  exit 2
fi

KERNEL_DIR="$(realpath "$1")"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ALLOWLIST_FILE="$SCRIPT_DIR/allowlist.txt"
HEADER_FILE="$KERNEL_DIR/init/hwid_allowlist.h"

[[ -f "$KERNEL_DIR/init/main.c" ]] || { echo "Kernel init/main.c not found" >&2; exit 1; }
[[ -f "$KERNEL_DIR/init/Makefile" ]] || { echo "Kernel init/Makefile not found" >&2; exit 1; }
[[ -f "$ALLOWLIST_FILE" ]] || { echo "HWID allowlist not found" >&2; exit 1; }

cp "$SCRIPT_DIR/hwid_lock.c" "$KERNEL_DIR/init/hwid_lock.c"

# Dry run: log what the kernel actually sees and keep booting instead of
# panicking. Enable with HWID_LOCK_DRY_RUN=1 or by creating hwid/DRYRUN.
# Use it once on any new device, read `dmesg | grep "HWID lock"`, then turn
# it back off. Never ship a dry-run build as the locked build.
DRY_RUN=0
if [[ "${HWID_LOCK_DRY_RUN:-0}" == "1" || -f "$SCRIPT_DIR/DRYRUN" ]]; then
  DRY_RUN=1
fi

cat > "$HEADER_FILE" <<'EOF'
/* Auto-generated by hwid/inject_hwid_lock.sh. */
#define HWID_LOCK_MAX_ID_LEN 129
EOF

if [[ $DRY_RUN -eq 1 ]]; then
  echo '#define HWID_LOCK_DRY_RUN 1' >> "$HEADER_FILE"
fi

cat >> "$HEADER_FILE" <<'EOF'
static const char *const hwid_allowlist[] __initconst = {
EOF

declare -A SEEN_HWIDS=()
HWID_COUNT=0
while IFS= read -r line || [[ -n "$line" ]]; do
  line="${line%%#*}"
  line="$(printf '%s' "$line" | tr '[:upper:]' '[:lower:]' | xargs)"
  [[ -n "$line" ]] || continue

  if [[ ! "$line" =~ ^[0-9a-z._:-]{4,128}$ ]]; then
    echo "Invalid HWID in $ALLOWLIST_FILE: $line" >&2
    exit 1
  fi
  [[ -z "${SEEN_HWIDS[$line]+x}" ]] || continue

  printf '\t"%s",\n' "$line" >> "$HEADER_FILE"
  SEEN_HWIDS[$line]=1
  HWID_COUNT=$((HWID_COUNT + 1))
done < "$ALLOWLIST_FILE"

if [[ $HWID_COUNT -eq 0 ]]; then
  echo "HWID allowlist is empty: $ALLOWLIST_FILE" >&2
  exit 1
fi

echo '};' >> "$HEADER_FILE"

grep -q '^obj-y.*hwid_lock\.o' "$KERNEL_DIR/init/Makefile" || \
  sed -i '/^obj-y.*main\.o/ s/$/ hwid_lock.o/' "$KERNEL_DIR/init/Makefile"

if ! grep -q 'void __init hwid_lock_verify(void);' "$KERNEL_DIR/init/main.c"; then
  sed -i '/^static int kernel_init(void \*);/a void __init hwid_lock_verify(void);' "$KERNEL_DIR/init/main.c"
fi

if ! grep -q 'hwid_lock_verify();' "$KERNEL_DIR/init/main.c"; then
  sed -i '/^[[:space:]]*setup_command_line(command_line);/a\	hwid_lock_verify();' "$KERNEL_DIR/init/main.c"
fi

grep -q 'hwid_lock.o' "$KERNEL_DIR/init/Makefile"
grep -q 'hwid_lock_verify();' "$KERNEL_DIR/init/main.c"
if [[ $DRY_RUN -eq 1 ]]; then
  echo "::warning::HWID lock injected in DRY RUN mode ($HWID_COUNT device(s)) - this kernel does NOT lock"
else
  echo "HWID lock injected with $HWID_COUNT allowed device(s)"
fi
